# Generated by Django 5.1.4 on 2025-09-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(blank=True, default='En cola', max_length=50, null=True),
        ),
    ]
